stages:
    - trigger downstream

# trigger lecture pipeline after commits to master
trigger lecture:
    stage: trigger downstream
    # TODO: Replace by general rules
    rules:
      - if: $CI_COMMIT_BRANCH == "feature/ci-trigger-lecture-build"
    trigger:
      project: dumux-repositories/dumux-lecture
      # TODO: replace by master
      branch: feature/ci-parallel-pipelines
      strategy: depend
