stages:
  - check-status
  - trigger
  - downstream modules

variables:
  IMAGE_REGISTRY_URL: $CI_REGISTRY/dumux-repositories/dumux-docker-ci
  DUMUX_CI_TRIGGER_LECTURE_BRANCH: master
  API_URL: https://git.iws.uni-stuttgart.de/api/v4/projects/31

# Cases in which to create pipelines at all. The trigger jobs may further
# specify how exactly they should be created in different situations.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH =~ /^(master|releases\/)/'

include:
  - local: .gitlab-ci/pipelinestatus.yml
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^(master|releases\/)/'

###################################################################################
# Stage 1: trigger the Dumux test pipelines                                       #
# In this stage, we trigger the test pipeline with different configurations, i.e. #
# different Dune versions, compilers, etc. Within merge requests, we create three #
# test pipelines including two different compilers and a full and minimal setup   #
# of dependencies. In all other situations, additional test jobs are created.     #
###################################################################################

# basic trigger job to start the test pipeline
.base-trigger:
  stage: trigger
  trigger:
    include: .gitlab-ci/default.yml
    strategy: depend
  variables:
    MR_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    REFERENCE_SHA: $CI_REFERENCE_SHA
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
  - if: $CI_PIPELINE_SOURCE == "pipeline"
    when: always
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: manual

# trigger for jobs that should not be created in merge requests
.non-mr-trigger:
  extends: .base-trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

#############################################
# pipelines to be created in merge requests #
full-dune-2.7-gcc:
  extends: .base-trigger
  variables:
    IMAGE: $IMAGE_REGISTRY_URL/full:dune-2.7-gcc-ubuntu-20.04

minimal-dune-2.7-gcc:
  extends: .base-trigger
  variables:
    IMAGE: $IMAGE_REGISTRY_URL/minimal:dune-2.7-gcc-ubuntu-20.04

full-dune-2.7-clang:
  extends: .base-trigger
  variables:
    IMAGE: $IMAGE_REGISTRY_URL/full:dune-2.7-clang-ubuntu-20.04

full-dune-master-gcc:
  extends: .base-trigger
  variables:
    IMAGE: $IMAGE_REGISTRY_URL/full:dune-master-gcc-ubuntu-20.04


##################################
# additional scheduled pipelines #
full-dune-master-clang:
  extends: .non-mr-trigger
  variables:
    IMAGE: $IMAGE_REGISTRY_URL/full:dune-master-clang-ubuntu-20.04


#########################################################
# Stage 2: trigger test pipelines of downstream modules #
#########################################################

# trigger lecture test
trigger lecture:
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "pipeline"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: downstream modules
  trigger:
    project: dumux-repositories/dumux-lecture
    branch: $DUMUX_CI_TRIGGER_LECTURE_BRANCH
    strategy: depend
  variables:
    DUMUX_MERGE_REQUEST_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    DUMUX_MERGE_REQUEST_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    DUMUX_COMMIT_SHA: $CI_COMMIT_SHA
    DUMUX_REFERENCE_SHA: $CI_REFERENCE_SHA
