default:
  image: $IMAGE

stages:
  - configure
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE=="parent_pipeline"

# variables that may be overwritten by the trigger
variables:
  TRIGGER_SOURCE: "undefined"
  MR_TARGET_BRANCH_NAME: "undefined"

select tests:
  stage: configure
  script:
    - |
      dunecontrol --opts=$DUNE_OPTS_FILE --current all
      if [[ "$TRIGGER_SOURCE" == "merge_request_event" ]]; then
          echo "Detecting changes w.r.t to target branch '$MR_TARGET_BRANCH_NAME'"
          python3 bin/testing/getchangedfiles.py -o changedfiles.txt -t origin/$MR_TARGET_BRANCH_NAME
          python3 bin/testing/findtests.py -o affectedtests.json --file-list changedfiles.txt --build-dir build-cmake
      else
          echo "Received '$TRIGGER_SOURCE' as pipeline trigger event"
          echo "Skipping test selection, build/test stages will consider all tests!"
          touch affectedtests.json
      fi
  artifacts:
    paths:
      - build-cmake
      - affectedtests.json
    expire_in: 3 hours

build dumux:
  stage: build
  script:
    - |
      pushd build-cmake
        make clean && make all
        if [ -s ../affectedtests.json ]; then
          python3 ../bin/testing/runselectedtests.py -c ../affectedtests.json -b
        else
          python3 ../bin/testing/runselectedtests.py --all -b
        fi
      popd
  artifacts:
    paths:
      - build-cmake
      - affectedtests.json
    expire_in: 3 hours
  needs:
    - job: select tests
      artifacts: true

test dumux:
  stage: test
  variables:
    OMPI_ALLOW_RUN_AS_ROOT: 1
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  script:
    - |
      pushd build-cmake
        if [ -s ../affectedtests.json ]; then
          python3 ../bin/testing/runselectedtests.py -c ../affectedtests.json -t
        else
          python3 ../bin/testing/runselectedtests.py --all -t
        fi
      popd
  needs:
    - job: build dumux
      artifacts: true
  artifacts:
    reports:
      junit: junit/dumux-cmake.xml
