default:
  image: $IMAGE

stages:
  - configure
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE=="parent_pipeline"

variables:
  TRIGGER_SOURCE: "unknown"
  MR_TARGET_BRANCH_NAME: "master"

select tests:
  stage: configure
  script:
    - |
      if [[ "$TRIGGER_SOURCE" == "merge_request_event" ]]; then
          dunecontrol --opts=$DUNE_OPTS_FILE --current all
          pushd build-cmake
            python3 ../bin/testing/findtests.py -f ../affectedtests.json -t origin/$MR_TARGET_BRANCH_NAME
          popd
      else
          echo "Skipping test selection, build/test stages will consider all tests!"
          echo "{}" >> ../affectedtests.json
      fi
  artifacts:
    paths:
      - affectedtests.json
    expire_in: 3 hours

build dumux:
  stage: build
  script:
    - dunecontrol --opts=$DUNE_OPTS_FILE --current all
    - |
      pushd build-cmake
        if [[ "$TRIGGER_SOURCE" == "merge_request_event" ]]; then
          python3 ../bin/testing/runselectedtests.py -c ../affectedtests.json -b
        else
          python3 ../bin/testing/runselectedtests.py --all -b
        fi
      popd
  artifacts:
    paths:
      - build-cmake
      - affectedtests.json
    expire_in: 3 hours
  needs:
    - job: select tests
      artifacts: true

test dumux:
  stage: test
  variables:
    OMPI_ALLOW_RUN_AS_ROOT: 1
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  script:
    - |
      pushd build-cmake
        if [[ "$TRIGGER_SOURCE" == "merge_request_event" ]]; then
          python3 ../bin/testing/runselectedtests.py -c ../affectedtests.json -t
        else
          python3 ../bin/testing/runselectedtests.py --all -t
        fi
      popd
  needs:
    - job: build dumux
      artifacts: true
  artifacts:
    reports:
      junit: junit/dumux-cmake.xml
