variables:
  CI_SCRIPT_FOLDER: '.'

check-pipeline-status:
  image: $IMAGE_REGISTRY_URL/full:dune-2.7-gcc-ubuntu-20.04
  stage: check-status
  script:
    - |
      getLastSuccessful() {
          python3 $CI_SCRIPT_FOLDER/.gitlab-ci/getpipelineinfo.py \
                      --access-token $CI_JOB_API_READ_TOKEN \
                      --project-api-url $API_URL \
                      --look-for latest-merge \
                      --print-format commit-sha
      }

      if ! python3 $CI_SCRIPT_FOLDER/.gitlab-ci/getpipelineinfo.py \
                            --access-token $CI_JOB_API_READ_TOKEN \
                            --project-api-url $API_URL \
                            --look-for HEAD \
                            --print-format pipeline-id; then
          echo "No successful pipeline found."

          REFERENCE_SHA=""
          if getLastSuccessful; then
              REFERENCE_SHA=$(getLastSuccessful);
              echo "Triggering new pipeline against reference commit $REFERENCE_SHA."
          else
              echo "Latest successful pipeline not found. Trigger complete pipeline."
          fi

          curl --request POST --form "token=$CI_JOB_TOKEN" \
                              --form ref=$CI_COMMIT_BRANCH \
                              --form "variables[CI_REFERENCE_SHA]=$REFERENCE_SHA" \
                              "$API_URL/trigger/pipeline"
      else
          echo "Found successful pipeline for the current state of the branch. Not testing again."
      fi
